### ISSUE TITLE
Microsoft Graph profile 'v.1.0' does not exist while running Add-MSIGraphPermissions.ps1

### ISSUE THREAD

**Issue by Karl-WE** [MSEndpointMgr/IntuneEnhancedInventory#10]
Installed Microsoft.Graph,
from the install-module Microsoft.Graph the module version is 1.11.1

[Add-MSIGraphPermissions.ps1](https://github.com/MSEndpointMgr/IntuneEnhancedInventory/blob/main/Add-MSIGraphPermissions.ps1)

The script outputs the following warning:

```
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.WindowsUpdates'. No cmdlets were loaded.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Financials'. No cmdlets were loaded.

```

**Comment by JankeSkanke** [comment]
If the graph module is not working as expected, I suggest you check here: https://github.com/microsoftgraph/msgraph-sdk-powershell
