### ISSUE TITLE
Imported sample workbooks won't run, missing parameters

### ISSUE THREAD

**Issue by Karl-WE** [MSEndpointMgr/IntuneEnhancedInventory#11]
repro:

open log analytics workspace
workbook > create a new workbook
pasting text from 
https://github.com/MSEndpointMgr/IntuneEnhancedInventory/tree/main/Sample%20Workbooks

Resulting error: 

```
This query could not run because some parameters are not set.
Please set: DeviceName

```
for the application workbook in addition other parameters are missing:

```
This query could not run because some parameters are not set.
Please set: Applications, Device, M365TimeRange

```
In the blog there is no guidance on what and where to specify.

The inventory script is running successfully and the needed custom tables are populated.

**Comment by escctrlbalt** [comment]
I have the same issue and I'm new to JSON and the whole Azure Workbook universe

**Comment by escctrlbalt** [comment]
> 

Hi, you have to link to correct resource

**Comment by escctrlbalt** [comment]
Hi, I think you have to link the correct Resource

**Comment by Karl-WE** [comment]
Hi I have figured it out with the assistance of Maurice. Kudos.
From our learnings we agreed that he will make some small changes to the article (documentation).

for transparency reasons, here is the solution to the issue aswell:
- One need to create the new workbook in the context of the Log Analytics Workspace, not in Azure Monitor or elsewhere
- the code from the workbook on github needs to be pasted into the advanced editor mode, not the simple KQL editor otherwise the reported issue (or others) will appear.
