### ISSUE TITLE
Intune Device Report Workbook - Hardware Inventory Report Issue "The Query returned no results"

### ISSUE THREAD

**Issue by escctrlbalt** [MSEndpointMgr/IntuneEnhancedInventory#13]
Hi,

I have implemented the inventory Script and BIOS Compliance Workbooks and everything look good, just the "Hardware Inventory Report" is showing "The Query returned no results" under "Device Inventory Details". I can see all the data in log analytics like TPM, Model, Uptime etc. so I guess there is an issue with the workbook. Any ideas?
Also it shows "1 HP, 1 Dell, 1 Microsoft" but with BIOS Compliance Workbook I get all the Models returned correctly.
Unfortunately I'm just a beginner when it comes to Azure, KQL, JSON and Workbooks. 

BR

Andreas

**Comment by hahman14** [comment]
So parts of the workbook rely on queries from multiple Tables. The Hardware Inventory Report by default relies on two tables to populate data:
DeviceInventory_CL is the custom table created by the script
IntuneDevices is a table created by the Intune service (assuming that you enabled)
                       Reports > Diagnostic Settings > Add diagnostic setting > check Devices (will take 24-48 hours to populate data)
Once Log Analytics has data from both tables, THEN you'll see data in that report.
The blog does not do any hand holding unfortunately. I had to learn the basics of KQL just to figure out how to manipulate these workbooks. In the end though, they do provide amazing data that can be very useful.

**Comment by escctrlbalt** [comment]
Thanks for heading me in the right direction. The Device Report under Diagnostics Settings was already enabled but the data was sent to a different workspace as I created a new one for the MSEndpointMgr Workbooks. I just added the workspace to the workbook as well and now it shows the data! Thx!
