### ISSUE TITLE
Software Inventory

### ISSUE THREAD

**Issue by jcameron4580** [MSEndpointMgr/IntuneEnhancedInventory#4]
First, I would say you guys did a great job.
My request would be that if software has been remove it should not show anymore in the report.
That would be great since in report we could see really what is out there, I know for some software you could have multiple version installed and they should show but for other if you remove or upgrade it should really reflect what is on the machine.
I do not know maybe delete what is already there and replace with the new one, or compare and remove or add.

Thanks,

**Comment by seanlillis** [comment]
I can second this, it would be great to get a Kusto query that only includes the latest app inventory for each computer excluding software that was previously installed but has since been removed. 

PS - thank you for this solution!

**Comment by seanlillis** [comment]
@jcameron4580 This query will only return the latest software installed per device, it will not return software that has been uninstalled or upgraded to a new version:

AppInventory_CL | summarize arg_max(TimeGenerated, *) by ComputerName_s, AppName_s
| partition hint.strategy=native by ComputerName_s
  (
    order by TimeGenerated
    | where row_rank(TimeGenerated) == 1
  )

**Comment by jcameron4580** [comment]
Would this be the code I need to modify:

AppInventory_CL
| where AppName_s in ({Applications}) or '*' in ({Applications})
| summarize arg_max(TimeGenerated, *) by ManagedDeviceID_g, AppName_s
| project ComputerName_s, AppName_s, AppVersion_s, TimeGenerated
| summarize count () by AppVersion_s

Also my applications stop at M, do you have any idea why ?

Regards,

**Comment by jcameron4580** [comment]
@seanlillis 
> @jcameron4580 This query will only return the latest software installed per device, it will not return software that has been uninstalled or upgraded to a new version:
> 
> AppInventory_CL | summarize arg_max(TimeGenerated, *) by ComputerName_s, AppName_s | partition hint.strategy=native by ComputerName_s ( order by TimeGenerated | where row_rank(TimeGenerated) == 1 )

Would this be the code I need to modify:

AppInventory_CL
| where AppName_s in ({Applications}) or '*' in ({Applications})
| summarize arg_max(TimeGenerated, *) by ManagedDeviceID_g, AppName_s
| project ComputerName_s, AppName_s, AppVersion_s, TimeGenerated
| summarize count () by AppVersion_s

Also my applications stop at M, do you have any idea why ?

Regards,
