### ISSUE TITLE
Application Inventory drop down box

### ISSUE THREAD

**Issue by th3nme** [MSEndpointMgr/IntuneEnhancedInventory#6]
I'm seeing an issue with the application dropdown ends at the letter G and doesn't show the full list of apps so I can't for example look at all of the office installs. I also cannot search for Microsoft Office with the filter at the top. 

![image](https://user-images.githubusercontent.com/32901493/166665047-20822108-896e-403e-bc9a-369d58b436c6.png)

If I look at the device specific list I can see it so the data is there but seems like there is a cap on items that show in the dropdown? 

![image](https://user-images.githubusercontent.com/32901493/166665148-e5e6fcea-8d5a-4ad6-8ad5-fa795c596167.png)

**Comment by th3nme** [comment]
I've kind of resolved it by changing the input field from a dropdown to raw text which allows me to look for a search string containing part of a software title. I also had to modify the queries running the charts.

**Comment by SkipToTheEndpoint** [comment]
Having the same issues as above. I've got tons of "Microsoft .NET Core xxx", "Microsoft .NET Framework xxx" and "Microsoft Visual C++ xxx" entries clogging up the list which would be much better to display if there was a way of condensing these multiple items down to their higher-level names, especially if there's a pie-chart to show version numbers from the AppVersion_s table.

I assume it would require some regex to function that way, but right now I can't even get to the bottom of the list with ~200 devices reporting back.

**Comment by JankeSkanke** [comment]
Workbooks are simply provided as samples. Closing this one
