### ISSUE TITLE
Application information with "unallowed" characters breaks report

### ISSUE THREAD

**Issue by thetootall** [MSEndpointMgr/IntuneEnhancedInventory#7]
I've implemented the proactive remediation script and on the Application Inventory Report it seems to be broken with the % character
![image](https://user-images.githubusercontent.com/19433966/171952937-2908fe5f-2e0a-4d1e-b0f6-a943d06ac7dc.png)
![image](https://user-images.githubusercontent.com/19433966/171952943-d3434739-6b2e-4945-84a5-f42aa1849775.png)

**Comment by JankeSkanke** [comment]
Sorry that the sample reports are not working 100% for you. If we build a more robust report, we could look into this. But workbooks should just be seens as samples for inspiration. #MustLearnKQL
